server:
  port: 9001
  servlet:
    context-path: /dubbo

test:
  service:
    version: 1.0.0

spring:
  application:
    name: cosumer
  datasource:
    url: jdbc:mysql://192.168.50.50/zego_recharge
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
dubbo:
  application:
    name: consumer
  registry:
    address: zookeeper://114.55.30.167:2181
  protocol:
    name: dubbo
    port: 20881