server:
  port: 9000

test:
  service:
    version: 1.0.0

spring:
  application:
    name: provider
  datasource:
    url: jdbc:mysql://192.168.50.50/zego_recharge
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456


dubbo:
  application:
    name: provider
  registry:
    address: zookeeper://114.55.30.167:2181
  protocol:
    name: dubbo
    port: 20881
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
