server:
  port: 9000

test:
  service:
    version: 1.0.0

spring:
  application:
    name: provider
dubbo:
  application:
    name: provider
  registry:
    address: zookeeper://114.55.30.167:2181
  protocol:
    name: dubbo
    port: 20881
